language: php
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  # Composer only updated in TravisCI containers when they build their images every month or so
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit tests